[package]
name = "aegis"
version = "0.1.3"
edition = "2018"
authors = ["Frank Denis <github@pureftpd.org>"]
description = "AEGIS authenticated cipher (AEGIS128L)"
keywords = ["aegis128", "cipher", "aead", "aes", "crypto"]
license = "MIT"
homepage = "https://github.com/jedisct1/rust-aegis"
repository = "https://github.com/jedisct1/rust-aegis"
categories = ["no-std", "cryptography"]
readme = "README.md"

[dependencies]
aes = { version = "0.7.5", features = ["hazmat"], optional = true }

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }
aes-gcm = "0.9.4"

[[bench]]
name = "benchmark"
harness = false

[features]
default = ["std", "aes_crate"]
aes_crate = ["aes"]
std = []
aesni = []

[profile.release]
codegen-units = 1
incremental = false
panic = "abort"
