[package]
name = "aegis"
version = "0.3.0"
edition = "2018"
authors = ["Frank Denis <github@pureftpd.org>"]
description = "AEGIS authenticated cipher (AEGIS128L)"
keywords = ["aegis128", "cipher", "aead", "aes", "crypto"]
license = "MIT"
homepage = "https://github.com/jedisct1/rust-aegis"
repository = "https://github.com/jedisct1/rust-aegis"
categories = ["no-std", "cryptography"]
readme = "README.md"

[target."cfg(not(any(all(target_arch = \"x86_64\", target_feature = \"aes\"),all(target_arch = \"x86\", target_feature = \"aes\"))))".dependencies.aes]
version = "0.8.2"
features = ["hazmat"]

[target.'cfg(not(pure_rust))'.build-dependencies]
cc = "1.0.79"

[dev-dependencies]
benchmark-simple = "0.1.7"
ascon-aead = "0.4.0"
aes-gcm = "0.10.1"
chacha20poly1305 = "0.10.1"

[[bench]]
name = "benchmark"
harness = false

[features]
default = ["std"]
pure-rust = []
std = []

[profile.release]
codegen-units = 1
incremental = false
panic = "abort"
